export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_RE_LOGIN = 'USER_RE_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_REGISTER = 'USER_REGISTER'

export const SHOP_LOGIN_SUCCESS = 'SHOP_LOGIN_SUCCESS'
export const SHOP_LOGIN_FAILED = 'SHOP_LOGIN_FAILED'
export const SHOP_LOGOUT = 'SHOP_LOGOUT'

